image: alpine:3.18

stages:
  - setup
  - import
  - validate
  - plan
  - apply
  - destroy

variables:
  TF_VAR_bucketname: "avik-tf-s3bucket-2025"
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"
  AWS_DEFAULT_REGION: "us-east-1"

before_script:
  - apk add --no-cache curl unzip
  - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.8.3/terraform_1.8.3_linux_amd64.zip
  - unzip terraform.zip && mv terraform /usr/local/bin/
  - terraform version

setup:
  stage: setup
  script:
    - echo "Terraform installed."

import:
  stage: import
  script:
    - terraform init
    - terraform import aws_s3_bucket.mybucket ${TF_VAR_bucketname} || echo "Already imported"
  artifacts:
    paths:
      - terraform.tfstate
      - terraform.tfstate.backup
      - .terraform
      - .terraform.lock.hcl

validate:
  stage: validate
  dependencies:
    - import
  script:
    - terraform init -backend=false
    - terraform validate

plan:
  stage: plan
  dependencies:
    - import
  script:
    - terraform init
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - tfplan

apply:
  stage: apply
  dependencies:
    - import
    - plan
  script:
    - terraform init
    - terraform apply -auto-approve tfplan
  when: manual
  environment:
    name: production
  only:
    - master

destroy:
  stage: destroy
  script:
    - terraform destroy -auto-approve
  when: manual
  only:
    - schedules
